# Generated by Django 4.0.5 on 2022-06-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='uuid',
        ),
    ]
